# Air配置文件 - Go热部署
# https://github.com/cosmtrek/air

root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  # 要编译的主文件
  cmd = "go build -o ./tmp/main.exe ."
  # 运行的二进制文件
  bin = "tmp/main.exe"
  # 要监听的文件后缀
  include_ext = ["go", "tpl", "tmpl", "html", "env"]
  # 排除的目录
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  # 排除的文件
  exclude_file = []
  # 排除不需要监听的文件后缀
  exclude_regex = ["_test.go"]
  # 排除不变文件
  exclude_unchanged = true
  # 监听.env文件变化
  include_file = [".env"]
  # 是否延迟触发构建
  delay = 1000
  # 发生错误时停止运行
  stop_on_error = true
  # 发送中断信号前的延迟
  kill_delay = 500

[log]
  # 显示日志时间
  time = true
  # 只显示主日志
  main_only = false

[color]
  # 自定义颜色
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  # 删除tmp目录启动时
  clean_on_exit = true